const BASE_PLAYER = Object.freeze({
  kind: 'player',
  species: 'human',
  bodyBuild: 'classic',
  skin: 'peach',
  hairStyle: 'spiky',
  hairColor: 'brown',
  expression: 'neutral',
  faceDetail: 'none',
  headgear: 'none',
  outfit: 'tunic',
  outfitTier: 'tier1',
  outfitColor: 'charcoal',
  weapon: 'sword',
  weaponTier: 'tier1',
  shield: 'none',
  shieldTier: 'tier1',
  palette: null,
});

export const SHADE_PILOTS = Object.freeze([
  Object.freeze({
    id: 'silver-knight',
    label: 'Silver plate knight',
    spec: Object.freeze({
      ...BASE_PLAYER,
      bodyBuild: 'sturdy',
      hairStyle: 'short',
      hairColor: 'black',
      expression: 'determined',
      headgear: 'plumed',
      outfit: 'plate',
      outfitTier: 'tier5',
      outfitColor: 'royal',
      weapon: 'rapier',
      weaponTier: 'tier5',
      shield: 'heater',
      shieldTier: 'tier5',
    }),
  }),
  Object.freeze({
    id: 'pale-wizard',
    label: 'Pale visible-face wizard',
    spec: Object.freeze({
      ...BASE_PLAYER,
      species: 'elf',
      bodyBuild: 'lean',
      skin: 'pale',
      hairStyle: 'long',
      hairColor: 'white',
      expression: 'surprised',
      faceDetail: 'glasses',
      headgear: 'circlet',
      outfit: 'robe',
      outfitTier: 'tier4',
      outfitColor: 'purple',
      weapon: 'staff',
      weaponTier: 'tier5',
      shield: 'arcane',
      shieldTier: 'tier4',
    }),
  }),
  Object.freeze({
    id: 'bone-reliquary',
    label: 'Undead bone equipment',
    spec: Object.freeze({
      ...BASE_PLAYER,
      species: 'undead',
      bodyBuild: 'classic',
      skin: 'pale',
      hairStyle: 'bald',
      hairColor: 'white',
      expression: 'angry',
      faceDetail: 'none',
      headgear: 'skullmask',
      outfit: 'necromancer',
      outfitTier: 'tier4',
      outfitColor: 'charcoal',
      weapon: 'club',
      weaponTier: 'tier5',
      shield: 'bone',
      shieldTier: 'tier5',
    }),
  }),
  Object.freeze({
    id: 'dark-ranger',
    label: 'Dark hair and outfit',
    spec: Object.freeze({
      ...BASE_PLAYER,
      species: 'beastkin',
      bodyBuild: 'heroic',
      skin: 'deep',
      hairStyle: 'messy',
      hairColor: 'black',
      expression: 'determined',
      faceDetail: 'warpaint',
      headgear: 'hood',
      outfit: 'ranger',
      outfitTier: 'tier5',
      outfitColor: 'charcoal',
      weapon: 'bow',
      weaponTier: 'tier5',
      shield: 'none',
    }),
  }),
  Object.freeze({
    id: 'custom-palette',
    label: 'Custom palette cleric',
    spec: Object.freeze({
      ...BASE_PLAYER,
      species: 'dwarf',
      bodyBuild: 'sturdy',
      skin: 'tan',
      hairStyle: 'braids',
      hairColor: 'ginger',
      expression: 'happy',
      faceDetail: 'beard',
      headgear: 'circlet',
      outfit: 'cleric',
      outfitTier: 'tier4',
      outfitColor: 'teal',
      weapon: 'mace',
      weaponTier: 'tier4',
      shield: 'round',
      shieldTier: 'tier4',
      palette: Object.freeze({
        skin: Object.freeze(['#b56c53', '#7a3f39']),
        hair: Object.freeze(['#d9c7a5', '#8b765d']),
        outfit: Object.freeze(['#4f7f70', '#2f4d48']),
      }),
    }),
  }),
  Object.freeze({
    id: 'artifact-guard',
    label: 'Unusual artifact equipment',
    spec: Object.freeze({
      ...BASE_PLAYER,
      species: 'celestial',
      bodyBuild: 'heroic',
      skin: 'brown',
      hairStyle: 'topknot',
      hairColor: 'blue',
      expression: 'determined',
      faceDetail: 'scar',
      headgear: 'crown',
      outfit: 'cape',
      outfitTier: 'tier5',
      outfitColor: 'teal',
      weapon: 'wand',
      weaponTier: 'tier5',
      shield: 'arcane',
      shieldTier: 'tier5',
    }),
  }),
  Object.freeze({
    id: 'dire-wolf',
    label: 'Dire Wolf',
    spec: Object.freeze({ kind: 'enemy', family: 'wolf', variant: 'dire' }),
  }),
  Object.freeze({
    id: 'aqua-slime',
    label: 'Bright Aqua Slime',
    spec: Object.freeze({ kind: 'enemy', family: 'slime', variant: 'aqua' }),
  }),
  Object.freeze({
    id: 'skeleton-mage',
    label: 'Colored-eye Skeleton Mage',
    spec: Object.freeze({ kind: 'enemy', family: 'skeleton', variant: 'mage' }),
  }),
  Object.freeze({
    id: 'ember-drake',
    label: 'Ember Drake',
    spec: Object.freeze({ kind: 'enemy', family: 'drake', variant: 'ember' }),
  }),
  Object.freeze({
    id: 'void-anglerfish',
    label: 'Voidlight Anglerfish',
    spec: Object.freeze({ kind: 'enemy', family: 'anglerfish', variant: 'voidlight' }),
  }),
  Object.freeze({
    id: 'stone-golem',
    label: 'Stone Golem',
    spec: Object.freeze({ kind: 'enemy', family: 'golem', variant: 'stone' }),
  }),
]);
